/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/inferno_b_test.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.VoxelMesh0.geometry}
        material={materials.Mat0}
        rotation={[Math.PI / 2, 0, 0]}
      />
    </group>
  );
}

useGLTF.preload("/inferno_b_test.glb");
